/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardMapRouteImport } from './routes/dashboard/map'
import { Route as DashboardDiagnosticsRouteImport } from './routes/dashboard/diagnostics'
import { Route as DashboardCommunityRouteImport } from './routes/dashboard/community'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as ApiIssuesRouteImport } from './routes/api.issues'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as DashboardIssuesIndexRouteImport } from './routes/dashboard/issues.index'
import { Route as DashboardIssuesCreateRouteImport } from './routes/dashboard/issues.create'
import { Route as DashboardIssuesIssueIdRouteImport } from './routes/dashboard/issues.$issueId'
import { Route as ApiIssuesIssueIdRouteImport } from './routes/api.issues.$issueId'
import { Route as ApiAuthMeRouteImport } from './routes/api.auth.me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthGoogleRouteImport } from './routes/api.auth.google'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMapRoute = DashboardMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDiagnosticsRoute = DashboardDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommunityRoute = DashboardCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiIssuesRoute = ApiIssuesRouteImport.update({
  id: '/api/issues',
  path: '/api/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIssuesIndexRoute = DashboardIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIssuesCreateRoute = DashboardIssuesCreateRouteImport.update({
  id: '/issues/create',
  path: '/issues/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIssuesIssueIdRoute = DashboardIssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiIssuesIssueIdRoute = ApiIssuesIssueIdRouteImport.update({
  id: '/$issueId',
  path: '/$issueId',
  getParentRoute: () => ApiIssuesRoute,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/features': typeof FeaturesRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/issues': typeof ApiIssuesRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/diagnostics': typeof DashboardDiagnosticsRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/issues/$issueId': typeof ApiIssuesIssueIdRoute
  '/dashboard/issues/$issueId': typeof DashboardIssuesIssueIdRoute
  '/dashboard/issues/create': typeof DashboardIssuesCreateRoute
  '/dashboard/issues/': typeof DashboardIssuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/issues': typeof ApiIssuesRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/diagnostics': typeof DashboardDiagnosticsRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/issues/$issueId': typeof ApiIssuesIssueIdRoute
  '/dashboard/issues/$issueId': typeof DashboardIssuesIssueIdRoute
  '/dashboard/issues/create': typeof DashboardIssuesCreateRoute
  '/dashboard/issues': typeof DashboardIssuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/features': typeof FeaturesRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/issues': typeof ApiIssuesRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/diagnostics': typeof DashboardDiagnosticsRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/issues/$issueId': typeof ApiIssuesIssueIdRoute
  '/dashboard/issues/$issueId': typeof DashboardIssuesIssueIdRoute
  '/dashboard/issues/create': typeof DashboardIssuesCreateRoute
  '/dashboard/issues/': typeof DashboardIssuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/impact'
    | '/login'
    | '/pricing'
    | '/resources'
    | '/sitemap.xml'
    | '/api/health'
    | '/api/issues'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/community'
    | '/dashboard/diagnostics'
    | '/dashboard/map'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/issues/$issueId'
    | '/dashboard/issues/$issueId'
    | '/dashboard/issues/create'
    | '/dashboard/issues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai'
    | '/community'
    | '/contact'
    | '/features'
    | '/impact'
    | '/login'
    | '/pricing'
    | '/resources'
    | '/sitemap.xml'
    | '/api/health'
    | '/api/issues'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/community'
    | '/dashboard/diagnostics'
    | '/dashboard/map'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/issues/$issueId'
    | '/dashboard/issues/$issueId'
    | '/dashboard/issues/create'
    | '/dashboard/issues'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai'
    | '/community'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/impact'
    | '/login'
    | '/pricing'
    | '/resources'
    | '/sitemap.xml'
    | '/api/health'
    | '/api/issues'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/community'
    | '/dashboard/diagnostics'
    | '/dashboard/map'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/google'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/issues/$issueId'
    | '/dashboard/issues/$issueId'
    | '/dashboard/issues/create'
    | '/dashboard/issues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiRoute: typeof AiRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  ImpactRoute: typeof ImpactRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiIssuesRoute: typeof ApiIssuesRouteWithChildren
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/map': {
      id: '/dashboard/map'
      path: '/map'
      fullPath: '/dashboard/map'
      preLoaderRoute: typeof DashboardMapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/diagnostics': {
      id: '/dashboard/diagnostics'
      path: '/diagnostics'
      fullPath: '/dashboard/diagnostics'
      preLoaderRoute: typeof DashboardDiagnosticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/community': {
      id: '/dashboard/community'
      path: '/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof DashboardCommunityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/issues': {
      id: '/api/issues'
      path: '/api/issues'
      fullPath: '/api/issues'
      preLoaderRoute: typeof ApiIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/issues/': {
      id: '/dashboard/issues/'
      path: '/issues'
      fullPath: '/dashboard/issues/'
      preLoaderRoute: typeof DashboardIssuesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/issues/create': {
      id: '/dashboard/issues/create'
      path: '/issues/create'
      fullPath: '/dashboard/issues/create'
      preLoaderRoute: typeof DashboardIssuesCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/issues/$issueId': {
      id: '/dashboard/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/dashboard/issues/$issueId'
      preLoaderRoute: typeof DashboardIssuesIssueIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/issues/$issueId': {
      id: '/api/issues/$issueId'
      path: '/$issueId'
      fullPath: '/api/issues/$issueId'
      preLoaderRoute: typeof ApiIssuesIssueIdRouteImport
      parentRoute: typeof ApiIssuesRoute
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCommunityRoute: typeof DashboardCommunityRoute
  DashboardDiagnosticsRoute: typeof DashboardDiagnosticsRoute
  DashboardMapRoute: typeof DashboardMapRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardIssuesIssueIdRoute: typeof DashboardIssuesIssueIdRoute
  DashboardIssuesCreateRoute: typeof DashboardIssuesCreateRoute
  DashboardIssuesIndexRoute: typeof DashboardIssuesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCommunityRoute: DashboardCommunityRoute,
  DashboardDiagnosticsRoute: DashboardDiagnosticsRoute,
  DashboardMapRoute: DashboardMapRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardIssuesIssueIdRoute: DashboardIssuesIssueIdRoute,
  DashboardIssuesCreateRoute: DashboardIssuesCreateRoute,
  DashboardIssuesIndexRoute: DashboardIssuesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiIssuesRouteChildren {
  ApiIssuesIssueIdRoute: typeof ApiIssuesIssueIdRoute
}

const ApiIssuesRouteChildren: ApiIssuesRouteChildren = {
  ApiIssuesIssueIdRoute: ApiIssuesIssueIdRoute,
}

const ApiIssuesRouteWithChildren = ApiIssuesRoute._addFileChildren(
  ApiIssuesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiRoute: AiRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  ImpactRoute: ImpactRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiIssuesRoute: ApiIssuesRouteWithChildren,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
